// <auto-generated />
using System;
using Contact.Microservice.Models.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Contact.Microservice.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230106142618_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Contact.Microservice.Models.Domain.IletisimBilgileri", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BilgiIcerigi")
                        .HasColumnType("text");

                    b.Property<string>("EmailAdresi")
                        .HasColumnType("text");

                    b.Property<Guid>("KisilerUUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Konum")
                        .HasColumnType("text");

                    b.Property<string>("TelefonNumarasi")
                        .HasColumnType("text");

                    b.HasKey("UUID");

                    b.HasIndex("KisilerUUID");

                    b.ToTable("IletisimBilgileri");
                });

            modelBuilder.Entity("Contact.Microservice.Models.Domain.Kisiler", b =>
                {
                    b.Property<Guid>("UUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Firma")
                        .HasColumnType("text");

                    b.Property<string>("Soyad")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UUID");

                    b.ToTable("Kisiler");
                });

            modelBuilder.Entity("Contact.Microservice.Models.Domain.IletisimBilgileri", b =>
                {
                    b.HasOne("Contact.Microservice.Models.Domain.Kisiler", "Kisiler")
                        .WithMany("IletisimBilgileri")
                        .HasForeignKey("KisilerUUID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kisiler");
                });

            modelBuilder.Entity("Contact.Microservice.Models.Domain.Kisiler", b =>
                {
                    b.Navigation("IletisimBilgileri");
                });
#pragma warning restore 612, 618
        }
    }
}
